name: todo
version: 1.0.0
description: This is a todo sample app for the Hive package.

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter

  hive: any
  hive_flutter: any

dev_dependencies:
  build_runner: ^2.1.0
  hive_generator: any

flutter:
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
