name: todo
version: 1.0.0
description: This is a todo sample app for the Hive package.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive:
  hive_flutter:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_flutter

dev_dependencies:
  build_runner: ^1.10.0
  hive_generator:
    git:
      url: git://github.com/hivedb/hive.git
      path: hive_generator

flutter:
  uses-material-design: true

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
